version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Expose the app on port 3000
    volumes:
      - .:/app       # Mount current directory to /app in container for live updates (optional)
    environment:
      - NODE_ENV=development  # Set the environment variable, e.g., development or production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
